#!/usr/bin/env bash
#
# Rebuild export trees from the repo root (canonical development tree):
#   ENTERPRISE/ — full application including licensed enterprise modules
#   PUBLIC/     — Community Edition only (GitHub open-source publish target)
#   PRIVATE/    — commercial / vendor-only (license signing, release ZIPs, secrets)
#
# Usage:
#   ./scripts/sync-public-private.sh
#   ./scripts/sync-public-private.sh --dry-run
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Resolve canonical dev tree (repo root). When this script lives under PUBLIC/scripts/,
# walk up to the parent that contains both app/ and PUBLIC/.
resolve_workspace_root() {
  if [ -f "$SCRIPT_DIR/../../app/__init__.py" ] && [ -d "$SCRIPT_DIR/../../PUBLIC" ]; then
    cd "$SCRIPT_DIR/../.." && pwd
    return
  fi
  if [ -f "$SCRIPT_DIR/../app/__init__.py" ]; then
    cd "$SCRIPT_DIR/.." && pwd
    return
  fi
  cd "$SCRIPT_DIR/.." && pwd
}

ROOT="$(resolve_workspace_root)"
PUBLIC_DIR="$ROOT/PUBLIC"
ENTERPRISE_DIR="$ROOT/ENTERPRISE"
PRIVATE_DIR="$ROOT/PRIVATE"
EXCLUDES_FILE="$ROOT/scripts/enterprise-public-excludes.txt"
PUBLIC_EXTRA_EXCLUDES=()
DRY_RUN=0

log() { printf '%s\n' "$*"; }
die() { log "ERROR: $*" >&2; exit 1; }

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      sed -n '2,16p' "$0"
      exit 0
      ;;
    *) die "Unknown option: $arg (try --help)" ;;
  esac
done

# Paths never copied into any export tree.
RSYNC_COMMON_EXCLUDES=(
  --exclude '.git/'
  --exclude 'PUBLIC/'
  --exclude 'ENTERPRISE/'
  --exclude 'PRIVATE/'
  --exclude 'firmgate-premium-licensing/'
  --exclude 'instance/'
  --exclude '.venv/'
  --exclude 'venv/'
  --exclude '.env'
  --exclude '.env.local'
  --exclude '__pycache__/'
  --exclude '*.pyc'
  --exclude '.DS_Store'
  --exclude '**/.DS_Store'
  --exclude 'dist/'
  --exclude '.cursor/'
  --exclude '*.bkp'
  --exclude '*.*.bkp'
  --exclude '**/*.bkp'
  --exclude '**/._*'
  --exclude 'app.log'
  --exclude 'Opensource_Intranet.code-workspace'
  --exclude 'upload.sh'
  --exclude 'push.sh'
  --exclude '.agent-transcripts/'
  --exclude 'assets/'
  --exclude 'AGENTS.md'
  --exclude 'tests/test_premium_license.py'
)

read_public_extra_excludes() {
  PUBLIC_EXTRA_EXCLUDES=()
  if [ ! -f "$EXCLUDES_FILE" ]; then
    return 0
  fi
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%#*}"
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [ -n "$line" ] || continue
    PUBLIC_EXTRA_EXCLUDES+=(--exclude "$line")
  done <"$EXCLUDES_FILE"
}

preserve_git_dir() {
  local target="$1"
  local backup=""
  if [ -d "$target/.git" ]; then
    backup="$(mktemp -d "${TMPDIR:-/tmp}/export-git.XXXXXX")"
    mv "$target/.git" "$backup/.git"
    printf '%s' "$backup"
  fi
}

restore_git_dir() {
  local target="$1"
  local backup="${2:-}"
  if [ -n "$backup" ] && [ -d "$backup/.git" ]; then
    mv "$backup/.git" "$target/.git"
    rmdir "$backup" 2>/dev/null || true
  fi
}

sync_enterprise() {
  log ">>> Rebuilding ENTERPRISE/ (full application + licensed modules)"
  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] Would rsync ${ROOT}/ → ${ENTERPRISE_DIR}/"
    return 0
  fi

  mkdir -p "$ENTERPRISE_DIR"
  local git_backup
  git_backup="$(preserve_git_dir "$ENTERPRISE_DIR")"
  rm -rf "$ENTERPRISE_DIR"
  mkdir -p "$ENTERPRISE_DIR"
  restore_git_dir "$ENTERPRISE_DIR" "$git_backup"

  rsync -a --delete "${RSYNC_COMMON_EXCLUDES[@]}" "$ROOT/" "$ENTERPRISE_DIR/"

  cat >"$ENTERPRISE_DIR/.enterprise-export-marker" <<'EOF'
This directory is generated by scripts/sync-public-private.sh from the parent workspace.
It contains the full Firmgate application including enterprise modules under app/enterprise/.
Do not edit here for day-to-day development — change the repo root and re-run ./sync.sh.
EOF

  cat >"$ENTERPRISE_DIR/README.md" <<'EOF'
# ENTERPRISE — full application export

Generated by `./sync.sh` from the repo root. Includes `app/enterprise/` (CRM, AI, Security Clearance, Resource Pool, Office 365, premium licensing).

Do not edit here — develop in the parent workspace, then re-run `./sync.sh`.

| Tree | Purpose |
|------|---------|
| **PUBLIC/** | Community Edition (GitHub) |
| **ENTERPRISE/** | Full licensed application |
| **PRIVATE/** | Signing keys, release ZIPs, secrets |
EOF
}

sync_public() {
  log ">>> Rebuilding PUBLIC/ (Community Edition — GitHub publish target)"
  read_public_extra_excludes

  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] Would rsync ${ROOT}/ → ${PUBLIC_DIR}/ with enterprise excludes"
    return 0
  fi

  mkdir -p "$PUBLIC_DIR"
  local git_backup
  git_backup="$(preserve_git_dir "$PUBLIC_DIR")"
  rm -rf "$PUBLIC_DIR"
  mkdir -p "$PUBLIC_DIR"
  restore_git_dir "$PUBLIC_DIR" "$git_backup"

  local -a rsync_args=("${RSYNC_COMMON_EXCLUDES[@]}")
  if [ "${#PUBLIC_EXTRA_EXCLUDES[@]}" -gt 0 ]; then
    rsync_args+=("${PUBLIC_EXTRA_EXCLUDES[@]}")
  fi
  rsync -a --delete "${rsync_args[@]}" "$ROOT/" "$PUBLIC_DIR/"

  cat >"$PUBLIC_DIR/.public-export-marker" <<'EOF'
This directory is generated by scripts/sync-public-private.sh from the parent workspace.
Community Edition only: enterprise modules under app/enterprise/ are omitted.
Do not edit here for day-to-day development — change the repo root and re-run ./sync.sh.
Push to GitHub from PUBLIC/ (./gitpush.sh at repo root does this automatically).
EOF

  if [ -f "$ROOT/README.public.md" ]; then
    cp -a "$ROOT/README.public.md" "$PUBLIC_DIR/README.md"
    log ">>> PUBLIC/README.md ← README.public.md (Community Edition readme for GitHub)"
  fi

  if [ -f "$ROOT/scripts/sanitize-public-export.py" ]; then
    log ">>> Sanitizing PUBLIC/ (remove enterprise traces)"
    python3 "$ROOT/scripts/sanitize-public-export.py"
  fi
}

sync_private() {
  log ">>> Rebuilding PRIVATE/ (commercial / vendor-only)"
  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] Would rm -rf ${PRIVATE_DIR} and repopulate vendor files"
    return 0
  fi

  if [ -d "$PUBLIC_DIR/RELEASES" ]; then
    mkdir -p "$PRIVATE_DIR/RELEASES"
    rsync -a --exclude '.DS_Store' "$PUBLIC_DIR/RELEASES/" "$PRIVATE_DIR/RELEASES/" 2>/dev/null || true
    rm -rf "$PUBLIC_DIR/RELEASES"
  fi

  PRIVATE_BACKUP="$(mktemp -d "${TMPDIR:-/tmp}/private-preserve.XXXXXX")"
  if [ -d "$PRIVATE_DIR/RELEASES" ]; then
    mv "$PRIVATE_DIR/RELEASES" "$PRIVATE_BACKUP/RELEASES"
  fi
  if [ -d "$PRIVATE_DIR/RELEASE" ]; then
    mv "$PRIVATE_DIR/RELEASE" "$PRIVATE_BACKUP/RELEASE"
  fi
  if [ -f "$PRIVATE_DIR/AGENTS.md" ]; then
    cp -a "$PRIVATE_DIR/AGENTS.md" "$PRIVATE_BACKUP/AGENTS.md"
  fi

  rm -rf "$PRIVATE_DIR"
  mkdir -p "$PRIVATE_DIR"

  if [ -d "$PRIVATE_BACKUP/RELEASES" ]; then
    mv "$PRIVATE_BACKUP/RELEASES" "$PRIVATE_DIR/RELEASES"
  fi
  if [ -d "$PRIVATE_BACKUP/RELEASE" ]; then
    mv "$PRIVATE_BACKUP/RELEASE" "$PRIVATE_DIR/RELEASE"
  fi
  if [ -f "$PRIVATE_BACKUP/AGENTS.md" ]; then
    cp -a "$PRIVATE_BACKUP/AGENTS.md" "$PRIVATE_DIR/AGENTS.md"
  fi
  rmdir "$PRIVATE_BACKUP" 2>/dev/null || true

  if [ -d "$ROOT/firmgate-premium-licensing" ]; then
    rsync -a "$ROOT/firmgate-premium-licensing/" "$PRIVATE_DIR/firmgate-premium-licensing/"
  else
    mkdir -p "$PRIVATE_DIR/firmgate-premium-licensing"
    log "NOTE: ${ROOT}/firmgate-premium-licensing not found — created empty placeholder."
  fi

  for f in upload.sh push.sh; do
    if [ -f "$ROOT/$f" ]; then
      cp -a "$ROOT/$f" "$PRIVATE_DIR/$f"
    fi
  done

  if [ -d "$ROOT/dist" ]; then
    mkdir -p "$PRIVATE_DIR/dist"
    rsync -a --exclude '.DS_Store' "$ROOT/dist/" "$PRIVATE_DIR/dist/" 2>/dev/null || true
  fi

  if [ -d "$ROOT/instance" ]; then
    log ">>> Copying instance/ snapshot into PRIVATE/instance/ (runtime data)"
    rsync -a --exclude '.DS_Store' "$ROOT/instance/" "$PRIVATE_DIR/instance/"
  fi

  if [ -f "$ROOT/.env" ]; then
    cp -a "$ROOT/.env" "$PRIVATE_DIR/.env"
    chmod 600 "$PRIVATE_DIR/.env" 2>/dev/null || true
  fi

  if [ -f "$ROOT/scripts/update.conf" ]; then
    mkdir -p "$PRIVATE_DIR/scripts"
    cp -a "$ROOT/scripts/update.conf" "$PRIVATE_DIR/scripts/update.conf"
  fi

  if [ -f "$ROOT/tests/test_premium_license.py" ]; then
    mkdir -p "$PRIVATE_DIR/tests"
    cp -a "$ROOT/tests/test_premium_license.py" "$PRIVATE_DIR/tests/test_premium_license.py"
  fi

  cat >"$PRIVATE_DIR/README.md" <<'EOF'
# PRIVATE — not for public GitHub

Rebuilt by `scripts/sync-public-private.sh`. Holds commercial and operational material.

| Item | Purpose |
|------|---------|
| `firmgate-premium-licensing/` | Ed25519 license signing (private key never in git) |
| `upload.sh` / `push.sh` | Push to private / internal git remotes |
| `dist/` | Build output mirror |
| `RELEASE/COMMUNITY/` | Community Edition upgrade ZIPs |
| `RELEASE/ENTERPRISE/` | Enterprise Edition upgrade ZIPs |
| `RELEASES/` | Legacy combined release ZIPs |
| `instance/`, `.env` | Local snapshots (confidential) |

Develop in the **repo root**; run `./sync.sh` after each change batch.
Publish open source from **PUBLIC/** only (`./gitpush.sh`).
Build edition ZIPs with `scripts/build_edition_packages.sh` → `PRIVATE/RELEASE/`.
EOF
}

cd "$ROOT"
sync_enterprise
sync_public
sync_private

log ""
log "Done."
log "  ENTERPRISE/ → full app ($(find "$ENTERPRISE_DIR" -type f 2>/dev/null | wc -l | tr -d ' ') files)"
log "  PUBLIC/     → Community Edition ($(find "$PUBLIC_DIR" -type f 2>/dev/null | wc -l | tr -d ' ') files)"
log "  PRIVATE/    → vendor & ops ($(find "$PRIVATE_DIR" -type f 2>/dev/null | wc -l | tr -d ' ') files)"
log ""
log "Next: ./gitpush.sh \"your message\"  (syncs PUBLIC/ then pushes to GitHub)"
